services:
  performancetest.db:
    image: ${DOCKER_REGISTRY-}performancetestdb
    container_name: performancetest.db
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
    - "31433:1433"
  performancetest.api:
    image: ${DOCKER_REGISTRY-}performancetestapi
    container_name: performancetest.api
    build:
      context: .
      dockerfile: PerformanceTest.API/Dockerfile
    ports:
      - "8080"
      - "8081"
    depends_on:
      - performancetest.db
    restart: on-failure

       
